### ISSUE TITLE
Invalid get index 'CONTROL_MOUSE' (on base: 'Node (game.gd)')

### ISSUE THREAD

**Issue by hiulit** [securas/Crackshot#1]
I'm using **Godot 3.1**. I don't know it the version has anything to do actually, but I may be relevant.

I had to add `CONTROL_TYPE` (the enum name) before every `CONTROL_GAMEPAD` and `CONTROL_MOUSE` (e.g. `game.control_type = game.CONTROL_TYPE.CONTROL_GAMEPAD`)

I think it happened the same with other enums.

**Comment by securas** [comment]
Thanks for reporting this. But it is a 3.0 project so one cannot expect it to work fully on Godot 3.1. It is not fully retro compatible.
