### ISSUE TITLE
Metal blocks not working properly

### ISSUE THREAD

**Issue by hiulit** [securas/Crackshot#2]
Using **Godot 3.1**.

All the `RigidBody2D` act weirdly...

I attach a video.

[rigid-body-weird.mp4.zip](https://github.com/securas/Crackshot/files/3022822/rigid-body-weird.mp4.zip)

P.S I have to say that I started a new project in Godot 3.1 and I've been having issues with `RigidBody2D` so maybe it's a bug or something https://www.reddit.com/r/godot/comments/b6k50k/rigidbody2d_not_colliding_properly_with/

**Comment by securas** [comment]
Same as the previous issue. This project needs to be used with Godot 3.0.
